apiVersion: v1
kind: PersistentVolume
metadata:
  name: easy-shop-pv
spec:
  capacity:
    storage: {{ .Values.mongodb.storageSize }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /data/easy-shop
