apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: easy-shop-pvc
  namespace: easy-shop-ns
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: ""
  resources:
    requests:
      storage: 4Gi
