apiVersion: v1
kind: ConfigMap
metadata:
  name: easy-shop-config
  namespace: {{ .Values.namespace }}
data:
  MONGODB_URI: {{ .Values.config.MONGODB_URI }}
  REDIS_URI: {{ .Values.config.REDIS_URI }}
  NODE_ENV: {{ .Values.config.NODE_ENV }}
