apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: easy-shop-db
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: easy-shop-db
  serviceName: easy-shop-db
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: easy-shop-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: easy-shop-db
        image: {{ .Values.mongodb.image }}
        ports:
        - containerPort: 27017
          name: easy-shop-db
        volumeMounts:
        - name: easy-shop-db-data
          mountPath: /data/db
        resources:
          requests:
            memory: "{{ .Values.mongodb.resources.requests.memory }}"
            cpu: "{{ .Values.mongodb.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.mongodb.resources.limits.memory }}"
            cpu: "{{ .Values.mongodb.resources.limits.cpu }}"
      volumes:
        - name: easy-shop-db-data
          persistentVolumeClaim:
            claimName: easy-shop-pvc
