apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: easy-shop-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.mongodb.storageSize }}
