{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: easy-shop-redis-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: easy-shop-redis
{{- end }}
