{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easy-shop-redis
  template:
    metadata:
      labels:
        app: easy-shop-redis
    spec:
      containers:
        - name: easy-shop-redis
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "{{ .Values.redis.resources.requests.memory }}"
              cpu: "{{ .Values.redis.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.redis.resources.limits.memory }}"
              cpu: "{{ .Values.redis.resources.limits.cpu }}"
          livenessProbe:
            exec:
              command:
              - redis-cli
              - ping
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            exec:
              command:
              - redis-cli
              - ping
            initialDelaySeconds: 5
            periodSeconds: 10
{{- end }}
