apiVersion: v1
kind: Secret
metadata:
  name: easy-shop-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  NEXTAUTH_SECRET: {{ .Values.secret.NEXTAUTH_SECRET }}
  JWT_SECRET: {{ .Values.secret.JWT_SECRET }}
